apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: chevereto
        - name: MYSQL_PASSWORD
          value: chevereto
        - name: MYSQL_ROOT_PASSWORD
          value: chevereto_root
        - name: MYSQL_USER
          value: chevereto
        image: mariadb:10.5.8
        name: db
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        securityContext:
          readOnlyRootFilesystem: false
          runAsUser: 23998
          runAsGroup: 32999
          allowPrivilegeEscalation: false
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "-h", "127.0.0.1", "-u", "chevereto", "-pchevereto", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: chevereto-db
      restartPolicy: Always
      volumes:
      - name: chevereto-db
        persistentVolumeClaim:
          claimName: chevereto-db-pvc        
